### ISSUE TITLE
TPU VM delete

### ISSUE THREAD

**Issue by remidebette** [googleapis/python-tpu#92] opened 2022-03-23 14:38 UTC
#### Environment details

  - OS type and version: linux and macOs
  - Python version: 3.9.7
  - `google-cloud-tpu` version: 1.3.2

#### Steps to reproduce

After creating a TPU VM thanks to https://stackoverflow.com/a/71244709/7433183
there is an issue when deleting it through the same python library.

(previously mentioned here: https://www.googlecloudcommunity.com/gc/AI-ML/Create-TPU-Node-Malformed-Name/td-p/397566)

#### Code example

```python
NAME = f"projects/{manifest.tpu.gcpProject}/locations/{manifest.tpu.gcpZone}/nodes/{manifest.name}"

client = tpu_v2alpha1.TpuClient()
        
request = tpu_v2alpha1.DeleteNodeRequest(
    name=NAME,
)

# Make the request
operation = client.delete_node(request=request)

logging.info("Waiting for operation to complete...")
response = operation.result()
```

#### Stack trace

The TPU VM is successfully deleted, but the python code eventually fails:

```
Cleaning TPU
Waiting for operation to complete...
Traceback (most recent call last):
File "/argo/staging/script", line 29, in <module>
response = operation.result()
File "/root/.local/lib/python3.9/site-packages/google/api_core/future/polling.py", line 132, in result
self._blocking_poll(timeout=timeout, **kwargs)
File "/root/.local/lib/python3.9/site-packages/google/api_core/future/polling.py", line 110, in _blocking_poll
retry_(self._done_or_raise)(**kwargs)
File "/root/.local/lib/python3.9/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
return retry_target(
File "/root/.local/lib/python3.9/site-packages/google/api_core/retry.py", line 190, in retry_target
return target()
File "/root/.local/lib/python3.9/site-packages/google/api_core/future/polling.py", line 88, in _done_or_raise
if not self.done(**kwargs):
File "/root/.local/lib/python3.9/site-packages/google/api_core/operation.py", line 170, in done
self._refresh_and_update(retry)
File "/root/.local/lib/python3.9/site-packages/google/api_core/operation.py", line 159, in _refresh_and_update
self._set_result_from_operation()
File "/root/.local/lib/python3.9/site-packages/google/api_core/operation.py", line 130, in _set_result_from_operation
response = protobuf_helpers.from_any_pb(
File "/root/.local/lib/python3.9/site-packages/google/api_core/protobuf_helpers.py", line 65, in from_any_pb
raise TypeError(
TypeError: Could not convert Any to Node
```

**Comment by parthea** [comment] 2022-03-23 19:38
Hello @remidebette,

Thanks for reporting this issue and providing a stack trace. I've reached out to the API team to propose an update to the [proto source file](https://github.com/googleapis/googleapis/blob/master/google/cloud/tpu/v2alpha1/cloud_tpu.proto) for the python client library. Googlers see cl/436800147. I'll update this issue once I have more information.

**Comment by parthea** [comment] 2022-03-24 10:24
The internal bug for this issue is b/226550050.

**Comment by parthea** [comment] 2022-09-13 14:51
I'm going to close this bug as the issue is on the backend and there are no improvements for the client library itself. Googlers see the internal bug b/226550050 for progress updates.

**Closed by parthea** 2022-09-13 14:51 UTC
Labels: type: bug, priority: p2, external, api: tpu

**Comment by remidebette** [comment] 2022-10-05 16:02
Hi,

I am still seeing the same issue with the `google-cloud-tpu` lib at the latest version `1.5.1`

```python
W
2022-10-05 15:58:33,820 [INFO] Cleaning TPU
2022-10-05 15:58:34,491 [INFO] Waiting for operation to complete...
Traceback (most recent call last):
  File "/argo/staging/script", line 29, in <module>
    response = operation.result()
  File "/usr/lib/python3.9/site-packages/google/api_core/future/polling.py", line 132, in result
    self._blocking_poll(timeout=timeout, **kwargs)
  File "/usr/lib/python3.9/site-packages/google/api_core/future/polling.py", line 110, in _blocking_poll
    retry_(self._done_or_raise)(**kwargs)
  File "/usr/lib/python3.9/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/usr/lib/python3.9/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/usr/lib/python3.9/site-packages/google/api_core/future/polling.py", line 88, in _done_or_raise
    if not self.done(**kwargs):
  File "/usr/lib/python3.9/site-packages/google/api_core/operation.py", line 170, in done
    self._refresh_and_update(retry)
  File "/usr/lib/python3.9/site-packages/google/api_core/operation.py", line 159, in _refresh_and_update
    self._set_result_from_operation()
  File "/usr/lib/python3.9/site-packages/google/api_core/operation.py", line 130, in _set_result_from_operation
    response = protobuf_helpers.from_any_pb(
  File "/usr/lib/python3.9/site-packages/google/api_core/protobuf_helpers.py", line 65, in from_any_pb
    raise TypeError(
TypeError: Could not convert Any to Node
```
